"""Maya's screen. The thing a judge and a shop owner both actually look at.

It is generated by the scheduled job, served from docs/ on GitHub Pages, and has to work
on a phone at six in the morning with no JavaScript.
"""
from __future__ import annotations

import os
import re

import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGE = os.path.join(ROOT, "docs", "index.html")


@pytest.fixture(scope="module")
def page():
    """Render a fresh page without touching the one that is committed and served.

    This used to shell out to render_page.py with the repository as the working directory,
    which rewrote a tracked file as a side effect of running the test suite. A test that
    edits the thing it is checking is not a test.
    """
    import importlib
    import tempfile
    render = importlib.import_module("tools.render_page")
    with tempfile.TemporaryDirectory() as tmp:
        out = os.path.join(tmp, "index.html")
        original, render.OUT = render.OUT, out
        try:
            assert render.main() == 0
            with open(out, "r", encoding="utf-8") as fh:
                return fh.read()
        finally:
            render.OUT = original


@pytest.fixture(scope="module")
def committed():
    with open(PAGE, "r", encoding="utf-8") as fh:
        return fh.read()


def test_the_page_regenerates_from_nothing_but_the_repository(page):
    assert len(page) > 2000


def test_rendering_a_page_for_a_test_does_not_touch_the_one_that_is_served():
    """The committed page is regenerated by the scheduled job, never by pytest.

    The earlier version of this asserted that the committed file contained the word
    "Checked", which is true whether or not the suite rewrote it. This watches the file.
    """
    import importlib
    import tempfile
    render = importlib.import_module("tools.render_page")
    before = os.stat(PAGE)
    with tempfile.TemporaryDirectory() as tmp:
        original, render.OUT = render.OUT, os.path.join(tmp, "index.html")
        try:
            assert render.main() == 0
        finally:
            render.OUT = original
    after = os.stat(PAGE)
    assert (before.st_mtime_ns, before.st_size) == (after.st_mtime_ns, after.st_size), \
        "rendering a page for a test rewrote the page that is served"


def test_the_committed_page_agrees_with_the_record_on_the_numbers(committed):
    """Everything except the timestamp, which moves on every run by design."""
    from tools.impact import figures
    f = figures()
    for claim in (f"<strong>{f['span']} days</strong>",
                  f"<strong>{f['changes']} changes</strong>",
                  f"<strong>{f['reaching']}</strong>"):
        assert claim in committed, claim


def test_the_page_is_one_file_with_no_external_requests(page):
    assert "<script" not in page.lower()
    assert "http://" not in page
    for url in re.findall(r'(?:src|href)="(https?://[^"]+)"', page):
        assert url.startswith("https://github.com/iamrobertmoore/still-working"), url


def test_the_page_names_maya(page):
    assert "Maya" in page


def test_the_page_opens_with_a_state_not_a_dashboard(page):
    body = page.split("<body>", 1)[1]
    first = re.search(r'class="state[^"]*">([^<]+)', body)
    assert first, body[:400]
    assert first.group(1).strip() in ("Still working.", "Something broke.")


def test_the_page_says_when_it_last_checked(page):
    assert re.search(r"Checked \d{2} \w+ \d{4} at \d{2}:\d{2} UTC", page)


def test_the_page_says_it_is_regenerated_by_a_job_not_by_hand(page):
    assert "Regenerated by a scheduled job, not by hand" in page


def test_the_page_states_what_it_cannot_see(page):
    assert "not what they have" in page and "deployed" in page


def test_the_page_admits_the_mapping_can_be_wrong(page):
    assert "can be wrong" in page


def test_the_page_links_to_the_source(page):
    assert "github.com/iamrobertmoore/still-working" in page


def test_the_page_has_a_dark_mode(page):
    assert "prefers-color-scheme: dark" in page


def test_the_page_declares_a_viewport_for_phones(page):
    assert 'name="viewport"' in page


def test_the_page_has_a_description_for_anyone_who_shares_it(page):
    assert 'name="description"' in page


def test_the_evidence_is_folded_away_rather_than_shown_to_her(page):
    assert "<details>" in page
    assert page.index("<details>") > page.index('class="state')


@pytest.mark.parametrize("word", ["endpoint", "parameter", "OpenAPI", "schema", "payload"])
def test_the_page_maya_reads_uses_none_of_the_suppliers_vocabulary(page, word):
    visible = re.sub(r"<style>.*?</style>", "", page, flags=re.S)
    visible = re.sub(r"<[^>]+>", " ", visible)
    assert word.lower() not in visible.lower()


def test_the_page_has_no_long_dashes(page):
    assert "—" not in page and "–" not in page


def test_the_page_reports_the_measurement(page):
    assert re.search(r"<strong>\d+ days</strong>", page)
    assert re.search(r"<strong>\d+ changes</strong>", page)


def test_the_page_applies_the_repeat_rule_like_everything_else(page):
    """It said three days reached her while the README said she is interrupted twice."""
    from tools.impact import figures
    f = figures()
    assert f["interruptions"] < f["reaching"], "this fixture no longer exercises the rule"
    assert "interrupted <strong>twice</strong>" in page or \
           f"interrupted <strong>{f['interruptions']}" in page, page[page.index("Over"):][:400]


def test_the_page_says_which_day_was_held_back_and_why(page):
    assert "you had just been told" in page


def test_the_page_speaks_to_maya_in_the_second_person(page):
    body = page.split("<body>", 1)[1]
    visible = re.sub(r"<style>.*?</style>", "", body, flags=re.S)
    visible = re.sub(r"<[^>]+>", " ", visible)
    assert " her shop " not in visible, "third person on a page addressed to her"
