# Generated by tools/sync_runtime.py. Edit agent/still_working.py, then regenerate.
from __future__ import annotations
from strands import tool
from strands.hooks import AfterToolCallEvent, BeforeToolCallEvent
from strands.interventions import Confirm, Deny, InterventionHandler, Proceed, Transform
from . import memory
from .notes import MayaNote, in_words, wrong_dates_in

SYSTEM = """You look after one person's shop. Her name is Maya.

You are given a supplier change and the routine of hers it touches. Decide whether it
actually stops that routine working. If it does, tell her what stopped, what it costs her,
and who to forward it to.

Writing to Maya:

* Never use the words endpoint, parameter, API or version. She does not have those words
  and does not need them. All of that goes in the part addressed to whoever fixes things.
* Call each supplier what she calls it. Use `vendor_address_as` when the supplier is the
  subject or object of a sentence, because it is phrased to fit one. `vendor_in_her_words`
  is her own first-person wording and only works when you are quoting how she talks about
  it. Never use the company's product name.
* Address the forwarded section to the person named in `business.who_fixes_things`, by
  name. Never write "your developer" when you have been given a name.
* Read `business.who_fixes_things` before telling her when something will be fixed. If that
  person is part time or not on retainer, do not promise same day.
* `business.how_maya_finds_out_today` is how she would otherwise have learned about this.
  It is usually worth one line, because it is the whole value of telling her now.
* No em dashes and no en dashes. Use a comma or start a new sentence.

Timing. Use `days_ago`, which is how long ago the supplier made the change. Say it plainly
in her terms, "seven weeks ago", "on Tuesday". Never invent recency. If you do not know
when something happened, do not imply that you do.

Certainty, and this is the one that decides whether she keeps reading these.

* That the supplier changed something is a FACT. It is in their own published record.
* That her routine is affected is an INFERENCE, from a mapping that was worked out during
  setup and carries a confidence.
* Say each at its real strength. At high confidence "this will have stopped working" is
  fair. At medium, write it as conditional: what the routine relies on, and what will have
  happened if it does. Never write "your X is broken" as a flat statement of fact when what
  you have is a contract change plus a mapping.
* The forwarded section is read by someone who can check. Give them the fact and the
  inference separately so they can verify the second one rather than trusting it.

If the mapping between her routine and the changed call is uncertain, say so plainly rather
than sounding sure."""


def is_a_note(text: str) -> bool:
    """Whether this tool result is a note Maya was actually shown.

    Positive recognition rather than a list of known failures. MayaNote always ends with
    the forwarding line, and nothing else the tool can return does.
    """
    return "forward this part to" in (text or "")


def _result_text(result) -> str:
    """The text of a tool result, whatever shape the framework hands it over in."""
    if isinstance(result, str):
        return result
    if isinstance(result, dict):
        for block in result.get("content", []) or []:
            if isinstance(block, dict) and "text" in block:
                return block["text"]
    return str(result or "")


def routine_to_report(impact: dict) -> dict | None:
    """Which of the broken routines this note is about.

    One function, used by both handlers, because they were choosing differently. The
    stamper took the first alphabetically and the decision took the first confident one,
    so on a day that broke two routines the note was stamped with the id of a routine it
    was not about. Nothing caught it except reading the demo output.
    """
    breaking = [r for r in impact.get("routines_touched", []) if r["has_breaking_change"]]
    if not breaking:
        return None
    confident = [r for r in breaking if r["mapping_confidence"] != "low"]
    return (confident or breaking)[0]


class StampTheFacts(InterventionHandler):
    """The model writes the words. The code writes the facts.

    Every factual error this project has shipped came from the same place: the model was
    holding a fact and a gap, and filled the gap. It was given a change dated 14 July and
    a `days_ago` of 51, and wrote "on 2026-05-24 (51 days ago)" under the word FACT. It
    had done arithmetic, got it wrong, and presented the result with more confidence than
    anything else in the note.

    The fix is not a firmer instruction. The fix is that the model is never the source of
    a fact that the system already knows. This handler runs before the decision handler
    and overwrites the factual fields of the outgoing note with the values from the
    deterministic layer, whatever the model put there.

    `Transform` mutates the event in place and lets the pipeline continue, so the handler
    that decides whether Maya hears anything at all sees the corrected call.
    """

    name = "stamp-the-facts"

    def __init__(self, impact: dict) -> None:
        self.impact = impact
        self.overwritten: list[str] = []

    def _stamp(self, event: BeforeToolCallEvent) -> None:
        payload = event.tool_use.get("input")
        if not isinstance(payload, dict):
            return
        subject = routine_to_report(self.impact)
        facts = {
            "routine_id": subject["routine_id"] if subject else "",
            "change_date": self.impact.get("date") or "",
            "days_ago": self.impact.get("days_ago"),
        }
        if subject and subject["mapping_confidence"] in ("medium", "low") and not payload.get("uncertainty"):
            payload["uncertainty"] = (
                "This depends on a link worked out during setup. The person who maintains "
                "the connection needs to check that your routine uses the part that changed.")
        for key, value in facts.items():
            if payload.get(key) not in (None, "", value):
                self.overwritten.append(key)
            payload[key] = value

    def before_tool_call(self, event: BeforeToolCallEvent, **kwargs):
        if event.tool_use["name"] != "send_to_maya":
            return Proceed(reason="not a note")
        return Transform(apply=self._stamp, reason=(
            "The date and the routine are not the model's to supply. They come from the "
            "vendor's own published record and from the deterministic matcher."))


class OnlyWhenItCostsHer(InterventionHandler):
    """The interruption rule, as a control rather than an instruction.

    Deny  : nothing she depends on is broken. She is never told.
    Deny  : she was told about this same routine within the last few days. Xero deleted
            the employee section on 24 April, restored it, and deleted it again on the
            29th. Two notes in five days about her payroll is how she learns to ignore
            the third. See agent/memory.py.
    Confirm: the ONLY routines broken were mapped at low confidence during setup, so a
             person checks before Maya is told her Monday number is wrong.
    Proceed: at least one routine we are confident about is broken.

    The ordering matters and I got it wrong first. Checking for low confidence before
    checking for a confident break meant one shaky mapping could hold up a certain
    problem behind a human. A thing we know is broken goes out now; the uncertainty
    rides along inside the note instead of gating it.
    """

    name = "only-when-it-costs-her"

    def __init__(self, impact: dict, approve_low_confidence: bool = True,
                 quiet_days: int = memory.QUIET_DAYS) -> None:
        self.impact = impact
        self.approve_low_confidence = approve_low_confidence
        self.quiet_days = quiet_days
        self.denied: list[str] = []
        self.asked: list[str] = []
        self.sent: list[str] = []
        self.flagged_uncertain: list[str] = []
        self.suppressed_repeat: list[str] = []
        self.history: list[dict] = []
        self.told_today: list[dict] = []
        self.delivered: list[str] = []
        self.refused: list[str] = []
        self.failed: list[str] = []
        self._pending: dict[str, dict] = {}
        self.agent = None

    def bind(self, agent) -> "OnlyWhenItCostsHer":
        """Take the agent as the record of what Maya has already been told.

        The agent is constructed with a session manager, so its state already carries the
        previous mornings by the time this is called. The ledger is read from there rather
        than from a side file, so there is one record and not two that can disagree.
        """
        self.agent = agent
        self.history = memory.ledger(agent)
        return self

    def _remember(self, routine: dict, use_id: str) -> None:
        """Record this note optimistically, and be ready to take it back.

        Two things have to be true at once and they pull in opposite directions.

        The within-morning repeat bound has to see this note *immediately*, because a model
        can ask to send three at once and a framework is free to run every `before` hook
        before any `after` hook. Waiting for the result meant all three were decided
        against an empty record and all three went out.

        The ledger must record only what actually rendered, because the tool can still
        refuse a note, and a refused note filed as told gets the model's corrected retry
        denied as a repeat of something Maya never saw.

        So: written at decision time, keyed on the tool use id, and retracted in
        `after_tool_call` if that call did not produce a note.
        """
        row = {"routine_id": routine["routine_id"],
               "change_date": self.impact.get("date"),
               "vendor": self.impact.get("vendor"),
               "what_maya_calls_it": routine.get("what_maya_calls_it")}
        self._pending[use_id] = row
        self.told_today.append(row)

    def _retract(self, row: dict, routine_id: str) -> None:
        if row in self.told_today:
            self.told_today.remove(row)
        for i in range(len(self.sent) - 1, -1, -1):
            if self.sent[i] == routine_id:
                del self.sent[i]
                break

    def after_tool_call(self, event: AfterToolCallEvent, **kwargs):
        if event.tool_use["name"] != "send_to_maya":
            return Proceed(reason="not a note")
        row = self._pending.pop(event.tool_use.get("toolUseId"), None)
        if row is None:
            return Proceed(reason="this call was never allowed through")

        rendered = _result_text(event.result)
        # A delivery is recognised by what a delivered note contains, not by the absence
        # of a known failure string. An exception inside the tool comes back as an error
        # message, and matching only on "REJECTED" filed that as a note Maya had been
        # sent, which then blocked the retry and, in the round-up, became her morning.
        if event.exception is not None or not is_a_note(rendered):
            (self.refused if rendered.startswith("REJECTED") else self.failed).append(
                row["routine_id"])
            self._retract(row, row["routine_id"])
            return Proceed(reason="nothing rendered, so nothing reached her")

        self.delivered.append(rendered)
        memory.record(self.agent, row["routine_id"], row["change_date"],
                      row["vendor"], row["what_maya_calls_it"])
        return Proceed(reason="she was told, and the ledger now says so")

    def before_tool_call(self, event: BeforeToolCallEvent, **kwargs):
        if event.tool_use["name"] != "send_to_maya":
            return Proceed(reason="reading only, nothing reaches her")
        use_id = event.tool_use.get("toolUseId") or ""

        touched = self.impact["routines_touched"]
        breaking = [r for r in touched if r["has_breaking_change"]]

        if not breaking:
            self.denied.append("nothing she depends on is broken")
            return Deny(reason=(
                "Do not send this. Of the "
                f"{self.impact['vendor_total_changes']} changes today, none broke a routine "
                "she depends on. Say nothing."))

        # `self.history` is what she was told on earlier mornings. `self.told_today` is
        # what has already gone out during this invocation. Both count, and only the
        # first did until a model that called the tool three times in a row put three
        # identical notes in front of her and nothing stopped it.
        seen_in = self.history + self.told_today
        repeat = next((r for r in breaking
                       if memory.told_recently(seen_in, r["routine_id"],
                                               self.impact.get("date"), self.quiet_days)),
                      None)
        already_today = any(r["routine_id"] == (repeat or {}).get("routine_id")
                            for r in self.told_today)
        if repeat and (len(breaking) == 1 or already_today):
            seen = memory.told_recently(seen_in, repeat["routine_id"],
                                        self.impact.get("date"), self.quiet_days)
            self.suppressed_repeat.append(repeat["routine_id"])
            self.denied.append(
                f"already told her about {repeat['routine_id']} "
                f"{seen['days_since']} days ago")
            return Deny(reason=(
                f"Do not send this. Maya was told about '{repeat['what_maya_calls_it']}' "
                f"{seen['days_since']} days ago and it is still the same routine and the "
                "same supplier. Sending it again teaches her the first one was noise. "
                "Say nothing."))

        confident = [r for r in breaking if r["mapping_confidence"] != "low"]
        if confident:
            top = routine_to_report(self.impact)
            self.sent.append(top["routine_id"])
            self._remember(top, use_id)
            if top["mapping_confidence"] == "medium":
                self.flagged_uncertain.append(top["routine_id"])
                return Proceed(reason=(
                    f"'{top['what_maya_calls_it']}' is broken. Send it, but the mapping is "
                    "medium confidence, so the note must say what we are unsure about. "
                    "Telling her something is wrong and sounding certain when we are not is "
                    "how she stops believing the next one."))
            return Proceed(reason=(
                f"'{top['what_maya_calls_it']}' is broken and we are confident the routine "
                "really leans on that call. Send it now."))

        low = breaking[0]
        self.asked.append(low["routine_id"])
        if self.approve_low_confidence:
            # A person said yes, so this note goes out and everything downstream that asks
            # "was anything sent" has to see it. It was in the ledger and not in `sent`,
            # which meant agent/morning.py silently produced no message on a morning where
            # a human had explicitly approved one.
            self.sent.append(low["routine_id"])
            self._remember(low, use_id)
        return Confirm(
            prompt=(f"We think this breaks '{low['what_maya_calls_it']}', but that is the only "
                    "thing broken and it was mapped at low confidence during setup. Tell Maya?"),
            response=self.approve_low_confidence,
        )


@tool
def send_to_maya(routine: str, headline: str, what_happened: str, what_it_costs: str,
                 how_late_normally: str, what_to_do: str, forward_to: str,
                 for_the_developer: str, uncertainty: str = "",
                 routine_id: str = "", change_date: str = "", days_ago: int | None = None) -> str:
    """Send Maya a note. This is the only thing that ever reaches her.

    Args:
        routine: what Maya calls the routine that broke.
        headline: one sentence, a consequence in her words.
        what_happened: two sentences, plain English, no vendor vocabulary.
        what_it_costs: what it costs her.
        how_late_normally: how late she would normally have found out.
        what_to_do: the single next action.
        forward_to: who fixes it.
        for_the_developer: the technical detail, one item per line.
        uncertainty: if the agent is not sure, what it is not sure about.
        routine_id: leave blank. Stamped by the system from the deterministic matcher.
        change_date: leave blank. Stamped by the system from the supplier's own record.
        days_ago: leave blank. Stamped by the system. Never calculate a date.
    """
    body = "\n".join([headline, what_happened, what_it_costs, how_late_normally,
                      what_to_do, for_the_developer, uncertainty])
    wrong = wrong_dates_in(body, change_date)
    if wrong:
        # Do not render it. Hand the mistake back so the model can correct itself, which
        # is what the deployed bundle does too. Stamping the right date into the note is
        # not enough on its own: the model can still assert a different one in its own
        # prose, and the first live run did exactly that, under the word FACT.
        bad = ", ".join(f"{d:02d}/{m:02d}" for m, d in sorted(wrong))
        return (f"REJECTED: this note mentions {bad}, which is not when this happened. "
                f"The supplier changed it on {in_words(change_date)}. Do not "
                "calculate dates. Say how long ago it was in words, or say nothing about "
                "when, and call the tool again.")

    # `routine` is not carried into the note. The headline already says what broke in her
    # words, and a second label above it read like a form. The argument stays because it
    # makes the model commit to one routine before it starts writing, and because the
    # stamped `routine_id` next to it is what the system actually uses.
    note = MayaNote(
        still_working=False, headline=headline,
        what_happened=what_happened, what_it_costs=what_it_costs,
        how_late_normally=how_late_normally, what_to_do=what_to_do,
        forward_to=forward_to, uncertain=bool(uncertainty), uncertainty=uncertainty,
        for_the_developer=[l for l in for_the_developer.splitlines() if l.strip()],
        change_date=change_date, days_ago=days_ago,
    )
    return note.render()
