#!/usr/bin/env python3
"""Package the canonical delivery controls for the isolated AgentCore bundle.

The runtime used to have a hand-maintained second implementation. Its date guard,
repeat rule and delivery accounting drifted from the tested local agent. Export the
actual definitions instead, and fail CI when the checked-in bundle is stale.
"""
from __future__ import annotations

import argparse
import ast
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUNDLE = ROOT / "runtime" / "app" / "StillWorking" / "sw_core"
NAMES = {"SYSTEM", "is_a_note", "_result_text", "routine_to_report", "StampTheFacts",
         "OnlyWhenItCostsHer", "send_to_maya"}
HEADER = '''# Generated by tools/sync_runtime.py. Edit agent/still_working.py, then regenerate.
from __future__ import annotations
from strands import tool
from strands.hooks import AfterToolCallEvent, BeforeToolCallEvent
from strands.interventions import Confirm, Deny, InterventionHandler, Proceed, Transform
from . import memory
from .notes import MayaNote, in_words, wrong_dates_in

'''


def expected_files() -> dict[str, str]:
    source = (ROOT / "agent" / "still_working.py").read_text()
    lines = source.splitlines(keepends=True)
    found, pieces = set(), []
    for node in ast.parse(source).body:
        name = getattr(node, "name", None)
        if isinstance(node, ast.Assign):
            name = getattr(node.targets[0], "id", None)
        if name not in NAMES:
            continue
        found.add(name)
        decorators = getattr(node, "decorator_list", [])
        start = min([node.lineno] + [d.lineno for d in decorators]) - 1
        pieces.append("".join(lines[start:node.end_lineno]).rstrip())
    if found != NAMES:
        raise RuntimeError(f"canonical definitions missing: {sorted(NAMES - found)}")
    files = {"controls.py": HEADER + "\n\n\n".join(pieces) + "\n",
             "__init__.py": '"""The same delivery controls as the local agent, packaged for AgentCore."""\n'}
    for name in ("memory.py", "notes.py"):
        files[name] = (f"# Generated from agent/{name} by tools/sync_runtime.py.\n" +
                       (ROOT / "agent" / name).read_text())
    return files


def main(check: bool = False) -> int:
    stale = []
    for name, content in expected_files().items():
        path = BUNDLE / name
        if check:
            if not path.exists() or path.read_text() != content:
                stale.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        print("Runtime controls differ from the local agent: " + ", ".join(stale))
        print("Run python tools/sync_runtime.py before testing or deploying.")
        return 1
    print("Runtime controls match the local agent." if check else "Packaged the local delivery controls for AgentCore.")
    return 0


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    raise SystemExit(main(ap.parse_args().check))
